### ISSUE TITLE
Unavailable Sensors After Adding Second Pool

### ISSUE THREAD

**Issue by OtisPresley** [dwradcliffe/home-assistant-waterguru#9]
Thanks for adding the capability to add a second pool. I got my second WaterGuru device a couple days ago. When I added it to the app and then reloaded HA, there are some sensors that are now unavailable as follows:

- Last Measured for the first pool
- Status for the first pool
- Free Chlorine for the second pool
- Free Chlorine Alert for the second pool

That is all I can see. The second pool is a covered spa, so there will be no sensor created for Cyanuric Acid or for Salt. Please let me know what else may be needed.

**Log message 1:**
`Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:595
integration: Sensor (documentation, issues)
First occurred: 4:50:12 PM (2 occurrences)
Last logged: 4:50:12 PM

Error adding entity sensor.waterguru_spa_free_chlorine for domain sensor with platform waterguru
Error adding entity sensor.waterguru_spa_free_chlorine_alert for domain sensor with platform waterguru
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
await coro
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
self.__async_calculate_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
if extra_state_attributes := self.extra_state_attributes:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waterguru/sensor.py", line 226, in extra_state_attributes
a[WaterGuruEntityAttributes.ADVICE] = m.get("alerts")[0].get("advice").get("action").get("summary")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'`

**Log message 2:**
`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/waterguru/sensor.py:226
integration: WaterGuru (documentation)
First occurred: 5:20:20 PM (1 occurrences)
Last logged: 5:20:20 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
self.__async_calculate_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1071, in __async_calculate_state
if extra_state_attributes := self.extra_state_attributes:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/waterguru/sensor.py", line 226, in extra_state_attributes
a[WaterGuruEntityAttributes.ADVICE] = m.get("alerts")[0].get("advice").get("action").get("summary")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'`

**Comment by dwradcliffe** [comment]
This is not surprising, but we can fix this. Can you send the current diagnostics file?

**Comment by dwradcliffe** [comment]
I've pushed a fix for these specific errors but we might run into more.

**Comment by OtisPresley** [comment]
[home-assistant_2024-10-06T16-56-49.921Z.log](https://github.com/user-attachments/files/17270260/home-assistant_2024-10-06T16-56-49.921Z.log)

Hi @dwradcliffe. here is the full log after updating the addon, enabling Debug Logging, and restarting HA. It doesn't look like it is producing errors, but the Last Measured and Status sensors on the original pool are still missing.

The Free Chlorine sensors for the second pool are now showing up normally. Thanks!

![image](https://github.com/user-attachments/assets/2980e87c-ef84-441f-ad66-0a6b6128fecc)

**Comment by OtisPresley** [comment]
Hi @dwradcliffe, this is getting more strange. I recently restarted for HA updates and now am seeing in the first pool, Saturation Index and Saturation Index Alert also missing with no log entries. I restarted HA again just to make sure, and they are still missing.

![image](https://github.com/user-attachments/assets/b19474e4-ad56-4831-bf4f-707177676f39)

**Comment by OtisPresley** [comment]
So, Saturation Index and Saturation Index Alert are back now. It looks like THAT part is related to the cassette needing to be replaced. Once I replaced it and it did another measurement, they became reachable again.

**Comment by OtisPresley** [comment]
Just checking in to see how the investigation is going? Please let me know if you need anything from me.

**Comment by OtisPresley** [comment]
Checking in to see if you have had any luck discovering the source of this issue? Please let me know if you need me to collect more information for you @dwradcliffe.

**Comment by dwradcliffe** [comment]
Can you share the diagnostics file?

<img width="362" alt="Download diagnostics" src="https://github.com/user-attachments/assets/c6a2648b-84bc-440c-9662-57dcb95935eb" />

**Comment by OtisPresley** [comment]
Thanks @dwradcliffe! I have included the diagnostics. Please let me know if you need anything else.

[config_entry-waterguru-01J6879DQF46HXRMM8EMJ0Q4V2.json](https://github.com/user-attachments/files/20840125/config_entry-waterguru-01J6879DQF46HXRMM8EMJ0Q4V2.json)

**Comment by dwradcliffe** [comment]
Found it! Try the latest version.

**Comment by OtisPresley** [comment]
Awesome @dwradcliffe! That got the majority. For some reason, saturation index and saturation index alert are still missing.

![Image](https://github.com/user-attachments/assets/5add2de3-8932-43b2-aa7a-2531939bcb37)

Here is a new diagnostic:

[config_entry-waterguru-01J6879DQF46HXRMM8EMJ0Q4V2.json](https://github.com/user-attachments/files/20841033/config_entry-waterguru-01J6879DQF46HXRMM8EMJ0Q4V2.json)

**Comment by dwradcliffe** [comment]
For some reason it seems that the api isn't returning that for you. I'm not sure how to debug that further.

**Comment by OtisPresley** [comment]
Strange. It was there until I added the second pool. However, it is not showing up in my app right now either. I have an issue with that SENSE and am waiting on the replacement to get here. I will update you on whether it comes back with the replacement unit or not.

**Comment by OtisPresley** [comment]
I got the new device and replaced the faulty one. Saturation Index is now working again! All sensors are not present. Thanks for all your help!
